CREATE DATABASE workshop2
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE users
(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    username VARCHAR(255) NOT NULL ,
    password VARCHAR(60) NOT NULL
);